/**
 * Auto-generated Zod schemas from FastAPI OpenAPI spec.
 *
 * This file will be generated by the generate-types script.
 * DO NOT manually edit this file.
 */

import { z } from 'zod'

// Placeholder schemas until generation is set up
export const WorkspaceSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  created_at: z.string().datetime(),
})

export const ProjectSchema = z.object({
  id: z.string().uuid(),
  workspace_id: z.string().uuid(),
  name: z.string(),
  project_type: z.string(),
  created_at: z.string().datetime(),
})

export const ImageSchema = z.object({
  id: z.string().uuid(),
  project_id: z.string().uuid(),
  filename: z.string(),
  storage_path: z.string(),
  width: z.number(),
  height: z.number(),
  created_at: z.string().datetime(),
})

export const AnnotationSchema = z.object({
  id: z.string().uuid(),
  image_id: z.string().uuid(),
  project_id: z.string().uuid(),
  annotator_id: z.string().uuid(),
  class_name: z.string(),
  data: z.record(z.any()),
  status: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
})

export type Workspace = z.infer<typeof WorkspaceSchema>
export type Project = z.infer<typeof ProjectSchema>
export type Image = z.infer<typeof ImageSchema>
export type Annotation = z.infer<typeof AnnotationSchema>
